.builds:
  stage: build
  allow_failure: true
  script:
    - echo "free -h"
    - free -h
    - echo "grep -c ^processor /proc/cpuinfo"
    - grep -c ^processor /proc/cpuinfo
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Release -DMUSPECTRE_RUNNING_IN_CI=ON ..
    - make -k
  artifacts:
    paths:
      - build
    expire_in: 1 day

.build:testing_gcc_mpi:
  extends: .builds

  image: registry.gitlab.com/muspectre/muspectre:debian_testing
  script:
    - echo "free -h"
    - free -h
    - echo "grep -c ^processor /proc/cpuinfo"
    - grep -c ^processor /proc/cpuinfo
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Release -DMUSPECTRE_MPI_PARALLEL=ON -DMPIEXEC_MAX_NUMPROCS=2 -DMPIEXEC_PREFLAGS="--oversubscribe;--allow-run-as-root" -DMUSPECTRE_RUNNING_IN_CI=ON ..
    - make -k

build:testing_gcc_setuptools:
  extends: .builds
  image: registry.gitlab.com/muspectre/muspectre:debian_testing
  script:
    - echo "free -h"
    - free -h
    - echo "grep -c ^processor /proc/cpuinfo"
    - grep -c ^processor /proc/cpuinfo
    - python3 setup.py build --disable-mpi

build:testing_clang:
  extends: .builds
  image: registry.gitlab.com/muspectre/muspectre:debian_testing
  script:
    - echo "free -h"
    - free -h
    - echo "grep -c ^processor /proc/cpuinfo"
    - grep -c ^processor /proc/cpuinfo
    - cd build
    - CXX=clang++ cmake -DCMAKE_BUILD_TYPE:STRING=Release -DMUSPECTRE_RUNNING_IN_CI=ON ..
    - make -k

build:stable_gcc:
  extends: .builds
  image: registry.gitlab.com/muspectre/muspectre:debian_stable

build:ubuntu16.04_gcc:
  extends: .builds
  image: registry.gitlab.com/muspectre/muspectre:ubuntu16.04

build:testing_gcc_split:
  extends: .builds
  image: registry.gitlab.com/muspectre/muspectre:debian_testing
  script:
    - echo "free -h"
    - free -h
    - echo "grep -c ^processor /proc/cpuinfo"
    - grep -c ^processor /proc/cpuinfo
    - cd build
    - cmake -DCMAKE_BUILD_TYPE:STRING=Release -DSPLIT_CELL=ON ..
    - make

.tests:
  stage: test
  script:
    - ls
    - cd build
    - ls -a
    - ctest --output-on-failure
    - make test
    - ls -ltr
    - ls Testing
  artifacts:
    when: always
    paths:
      - build/tests/test_results*.xml
      - build/tests/libmufft/test_results*.xml
      - build/tests/libmugrid/test_results*.xml
    reports:
      junit:
      - build/tests/test_results*.xml
      - build/tests/libmufft/test_results*.xml
      - build/tests/libmugrid/test_results*.xml

.test:testing_gcc_mpi:
  image: registry.gitlab.com/muspectre/muspectre:debian_testing
  extends: .tests
  dependencies:
    - build:testing_gcc_mpi

test:testing_gcc_setuptools:
  image: registry.gitlab.com/muspectre/muspectre:debian_testing
  extends: .tests
  dependencies:
    - build:testing_gcc_setuptools
  script:
    - python3 setup.py install --user --disable-mpi
    - cd tests/libmufft
    - python3 python_binding_tests.py

test:testing_clang:
  image: registry.gitlab.com/muspectre/muspectre:debian_testing
  extends: .tests
  dependencies:
    - build:testing_clang

test:stable_gcc:
  image: registry.gitlab.com/muspectre/muspectre:debian_stable
  extends: .tests
  dependencies:
    - build:stable_gcc

test:ubuntu16.04_gcc:
  image: registry.gitlab.com/muspectre/muspectre:ubuntu16.04
  extends: .tests
  dependencies:
    - build:ubuntu16.04_gcc

test:testing_gcc_split:
 image: registry.gitlab.com/muspectre/muspectre:debian_testing
 extends: .tests
 dependencies:
    - build:testing_gcc_split

